JoinSEEDS/seeds-smart-contracts

src/seeds.exchange.cpp
This is temporary so we can clear the table
=> Changed reset so it removes data, but doesn't set it

include/seeds.policy.hpp, include/tables.hpp, src/seeds.policy.cpp, test/policy.test.js
As per Antonio, requirement is that we have > 1 policy per user - one for each device
Also each account may be on multiple user devices.
- Changed policy table to be not scoped (as that was useless)
- renamed for convenience
- Added auto id to table
- Added account as secondary index
- Added remove - we will need this eventually
- Updated unit tests
=> Policy refactor

.gitignore, include/seeds.exchange.hpp, scripts/helper.js, src/seeds.exchange.cpp, test/exchange.test.js
Starts at 0.011 USD / Seeds
50 rounds of 1,100,000.00 SEEDS
Increase 3.3% per round
Specification in [Master - Seeds Distribution](https://docs.google.com/spreadsheets/d/1uf_8E0cSqB0qw9kWzFMgqlyDwqoJRmPig5bbhR2puJo/edit#gid=1993216757)
- Rounds added
- Init rounds action
- addround action
- initsale action
- Updating the price before and after sale
- Updating price in config
- Removed ability to manually set USD price
- Unit test tests for all cases
- Unit tests fro purchases crossing over rounds, e.g. buying 1.5 rounds, or buying 0.1 of one round and 0.3 of the next round
- Edge cases (running out of rounds)
=> Token Sale Rounds 1 - 50

include/seeds.harvest.hpp, src/seeds.harvest.cpp, test/harvest.test.js
calculations are now 100 buckets, from 0 - 99.
Nobody has a score of 100
Previously, we had buckets from 0 - 99 with 1 user less in the 0 bucket and one additional user with a score of 100.
=> All scores are 0 - 99 (not 0 - 100)

.gitignore, include/seeds.accounts.hpp, include/seeds.harvest.hpp, include/seeds.proposals.hpp, include/utils.hpp, scripts/helper.js, scripts/seeds.js, src/seeds.accounts.cpp, src/seeds.harvest.cpp, src/seeds.history.cpp, src/seeds.proposals.cpp, src/seeds.scheduler.cpp, src/seeds.settings.cpp, test/accounts.test.js, test/harvest.test.js, test/onboarding.test.js, test/proposals.test.js, test/token.test.js
All scores are calculated in a new way and found here now
Score | Contract | Table | Table Fields
------------ | ------------- | ------------- | -------------
Reputation points and score | accts.seeds | rep | rep, rank
Community Building Score | accts.seeds | cbs | community_building_score, rank
Planted Score | harvst.seeds | planted | planted, rank
Transaction Score | harvst.seeds | txpoints | points, rank
Contribution Score | harvst.seeds | cspoints | contribution_points, rank
Deploy migration contract to clear
=> Scores refactoring

src/seeds.history.cpp
Using the user account as unique value for the delayed transaction
Previous was not unique because the table was scoped by user, that means different users would get in each others way
If there are many user updates, we collapse them by canceling the previous ones
=> History Hotfix

include/seeds.settings.hpp, src/seeds.settings.cpp, test/referendums.test.js
- Added action `confwithdesc`. This action is called inside `reset` action and configures a parameter with a description. We added this action to not affect referendums contract as it is using `configure` action.
- I also created another branch called migrate/clean-settings: https://github.com/JoinSEEDS/seeds-smart-contracts/tree/migrate/clean-settings. In this branch there is an action in settings contract called `migrate` which only deletes the `config` table.
> Question: Since many contracts depend on config_table - do we need to recompile and redeploy them all too?
>
No, you don't need to neither recompile nor redeploy them as long as they don't need to access to the new `description` parameter.
I also noticed that these contracts didn't pass all their tests successfully:
- lending
- …
=> High, medium, and low thresholds #60

include/seeds.proposals.hpp, include/utils.hpp, scripts/helper.js, src/seeds.proposals.cpp, src/seeds.scheduler.cpp, src/seeds.settings.cpp, test/proposals.test.js
- Added `decayvoices` and `decayvoice` actions
- Added new settings
- Added to scheduler reset
Amazingly, the voice decay timestamp was already in there so no migration of tables - foresight level visionary ;)
=> Feature/simple vote depreciation - #114

include/seeds.forum.hpp, include/utils.hpp, src/seeds.accounts.cpp, src/seeds.forum.cpp, src/seeds.harvest.cpp, src/seeds.organization.cpp
This happens when rankings / points change while the rank is in progress. 
For example, user A has 5 points, rank runs and sets user A's rank to 0, the ranking ends at position 200
User A receives another 20 points from somewhere
Ranking continues at position 200, but now user A is located at position 450 (for example) and will eventually be ranked again - maybe at rank 15 for example. 
That rank is correct - that's fine - but we are counting up on how many users we have ranked to determine rank, and so the count is now 1 too many, and when we get to the end of the table, count == size, and rank is set to 100.
The rank will even out again on the next run of the ranking.
The same thing will happen in many other ways, but they're less visible - e.g. the rank for someone will be too high or …
=> limit rank to 99

include/seeds.proposals.hpp, src/seeds.proposals.cpp, test/proposals.test.js
- Added new scope for alliance proposals
- Added new methods to modify voices
- Added tests
The action `migratevoice` is there only to take all the existing voice entries and copy them into the new scope. But the fact that a user does not exist in the voice table scoped by `alliance` does not affect the rest of the methods. Indeed some methods can add the missing voice entry for a user that already has voice scoped by `contract's name`.
=> Separate voice distributions for Alliance vs Campaign type proposals #137

include/seeds.proposals.hpp, src/seeds.proposals.cpp
the quorum is dynamic and always changing depending on the number of proposals, number of eligible voters, and their vote power. Therefore we only check quorum on the initial vote. Once a proposal has been voted in and is in eval stage, we only check unity, in case someone changed their mind. But we don't check quorum.
@IanMendozaJaimes  please check
=> bugfix: don't check quorum for evaluate stage proposals

include/seeds.accounts.hpp, include/seeds.harvest.hpp, include/seeds.history.hpp, include/seeds.organization.hpp, include/utils.hpp, scripts/helper.js, src/seeds.accounts.cpp, src/seeds.harvest.cpp, src/seeds.history.cpp, src/seeds.organization.cpp, src/seeds.scheduler.cpp, src/seeds.settings.cpp, test/accounts.test.js, test/harvest.test.js, test/history.test.js, test/organization.test.js, test/scheduler.test.js
- Added new tables to store daily transactions and total points per day. Added a totals table
- Added QEV calculation
- Modified transaction points calculation for orgs and users
- Modified number of transactions validation for becoming a resident/citizen user or reputable/regenerative org
- Added tests
I also pushed a branch called migration/unified-qev-calculation, there I put a method called `migrateusers`, that action will copy the transactions for users and orgs and store them in the new tables using the new criteria to count transactions. The method doesn't clean the old transactions tables just in case.
=> Unified QEV Calculation #167

include/seeds.harvest.hpp, scripts/helper.js, src/seeds.harvest.cpp, src/seeds.scheduler.cpp, test/harvest.test.js
- Added cs for bioregions
- Added tests
- Added `rankbiocss` to scheduler
I added the table `bioregion_cs_temporal_table` as an auxiliary table for storing the sum of the users' contribution points, and it is cleaned every time the bioregions are ranked with the function `rankbiocss`.
=> Bioregion Contribution Score #161

include/seeds.proposals.hpp, src/seeds.proposals.cpp, test/proposals.test.js
The way the action `mimicvote` was calling the function `vote_aux` was in the same transaction so if some delegator for some reason can not vote, then the whole action will fail. 
One example of that could be when the user A voted trust for a proposal that is now in evaluation phase, then user B delegates its voice to user A, and then user A votes distrust. This will cause a fail because B can't vote for the proposal.
That's why I added the action `voteonbehalf`, so it could be called in a deferred transaction inside `mimicvote`, in that way if a particular vote fails the rest of the mimicked votes don't.
=> Bug fix in vote delegation

include/seeds.proposals.hpp, src/seeds.proposals.cpp, src/seeds.settings.cpp, test/proposals.test.js
#207 
- Disable quorum check in code for initial deploy - all current proposals are passing the existing quorum calculation so this does not impact any existing proposal in this cycle. 
- Deploy Proposals, Settings
- Update settings
- Manually set the old unity setting back to 80%
- Call migration action on proposals
- run moon cycle as usual
- Re-enable quorum check
- Deploy proposals
- Update settings
- Added `cyclestats` and `cycvotedprps` tables
- Added tests
The `cyclestats` table is the table that you described in the issue. The quorum base is being calculated using the value `total_voice_cast` which is the sum of all the voice amount spent during the cycles. I got a bit confused when you say "avg votes cast" that's why I added the field `num_votes` which is the sum of all the …
=> Quorum is generated from the avg voice cast form the last 2 cycles #207

include/contracts.hpp, include/seeds.gratitude.hpp, scripts/helper.js, src/seeds.gratitude.cpp, src/seeds.settings.cpp, test/gratitude.test.js
This is the first implementation of the SEEDS gratitude token.
The basic idea is that you can allocate some funds to the `gratz.seeds` contract, then everyone gets some gratitude tokens to share. At the end of the round, the amount of SEEDS resting at the contract gets split among everyone that received gratitude during the round, in proportion to how much they got, for example:
If the round volume was 1000 gratitude tokens, and you got 100 in total, you get 100/1000 (1/10) of the stash of SEEDS.
When the round ends, all gratitude tokens available for giving are reset to the original quantity, and all earned tokens are back to zero for all users.
Still need to schedule the "newround()" action on seeds.scheduler, for once every cycle.
- contracts to deploy: settings, gratitude
- …
=> Gratitude token contract

src/seeds.token.cpp, test/token.test.js
Minor bugfix - if transactions number from planted is less than minimum, make it minimum
Bug scenario
Minimum transaction = 7
Multiplier = 1x
User has 1 Seeds planted, tx limit would now be 1 in the old code
In the new code, it's never below the minimum.
=> Fix min trx value

docs/bioregion.html, include/contracts.hpp, include/seeds.harvest.hpp, include/seeds.history.hpp, include/seeds.onboarding.hpp, include/seeds.region.hpp, scripts/helper.js, scripts/seeds.js, src/seeds.harvest.cpp, src/seeds.history.cpp, src/seeds.onboarding.cpp, src/seeds.region.cpp, src/seeds.scheduler.cpp, src/seeds.settings.cpp, test/accounts.test.js, test/harvest.test.js, test/history.test.js, test/onboarding.test.js, test/region.test.js, test/scheduler.test.js
- Renamed bioregions contract to regions
- Renamed methods and settings that included a reference to "bio"
- Added new index in the new regions table
- Changed the name of some fields in the regions contract
- Changed the domain ".bdc" to ".rdc"
I think no migration is needed because those tables were empty by the time I created this pull request.
There was an account in `helper.js` called "bdc", I changed to "rdc", that would require the creation of a new account.
I didn't change the contract's name on the nets, so it is still called "bio.seeds".
- region / bioregion
- onboarding
- history
- harvest
- scheduler
- settings
- updateSettings
- updateScheduler
Unit tests work in this branch
Unit tests work in merged master branch
=> Rename bioregions contract to regions

include/seeds.history.hpp, include/seeds.organization.hpp, include/utils.hpp, scripts/helper.js, src/seeds.accounts.cpp, src/seeds.history.cpp, src/seeds.organization.cpp, src/seeds.settings.cpp, test/history.test.js, test/organization.test.js
- Added new methods for orgs to update their status
- Changed the way validations were made for org status
- Added new settings
- Added new table to history contract and deleting `reputable` and `regen` tables, migration is not needed since those tables were empty
- Changed transactions multiplier in history
- Fixed rep multiplier in `addregen` and `subregen` actions
- Added tests for orgs
#242 
**Contracts**
updateSettings (yes)
updateScheduler, not needed
migration, not needed
=> Feature/five level of organizations #242

src/seeds.gratitude.cpp
A new row for a new round was not being created. Simple change.
=> Fix gratitude: update stats when creating new round

include/seeds.exchange.hpp, src/seeds.exchange.cpp, test/exchange.test.js
we want to be able to update the volume to reflect the higher price starting at round 50
This is in the Seeds game guide.
https://docs.google.com/document/d/11040FOvIJIsjXl0gvkBLRegOIWdYM_04OnXsXzHliTU/edit#heading=h.30j0zll
=> updatevol action added

src/seeds.accounts.cpp
Fixes #317 
- Added validations in accounts::adduser and accounts::update to enforce the new limits for strings
The new limits  are:
string nickname; \  ====> Limit 64
string image; \ == Limit 512 
string story; => Limit 7000
string roles; \ Limit 512
string skills; \ Limit 512
string interests; \ Limit 512
Only the accounts contract was modified.
This modification doesn't affect the way onboarding works
=> Limit sizes of String in Account #317

include/seeds.accounts.hpp, src/seeds.accounts.cpp, test/accounts.test.js
Fixes #318 
- This one includes two functions to migrate the users table and force it  to use the new string limits: 
- migusersizes: traverse all the users table enforcing the new limits
- migusrsize: finds one user and enforce the new limits for that user
I added the migusrsize because I don't know if the user with 132 kB in a string will cause problems in the other function so maybe it's a good idea to process that user apart from the rest.
Both functions don't check for the story limits because according to @n13 the longest string for the `story` is 6000 characters long and the limit is 7000
=> Migrate user accounts to limit String size #318

include/seeds.scheduler.hpp, scripts/helper.js, src/seeds.scheduler.cpp, test/scheduler.test.js
- Added moonops table
- Added `configmoonop` action and modified `removeop` and `pauseop` to interact with the moon operations
- Removed action `confirm` this action wasn't helping to confirm the correct execution, it was just consuming cpu time
Modified contracts:
No migrations nor permissions update is needed
=> Add moon phase to scheduler #239

include/seeds.history.hpp, src/seeds.history.cpp, test/history.test.js, test/token.test.js
- Added a table to store the ids to use them in deferred transactions in history
- Added a new table to store the processed transactions. This is needed for the correct qev and trx points calculation.
Contracts modified:
No migrations or settings are needed
=> Token transfer bug - not all actions are recorded in history #316

include/contracts.hpp, include/seeds.escrow.hpp, include/seeds.harvest.hpp, include/seeds.pool.hpp, include/tables/config_table.hpp, include/tables/size_table.hpp, scripts/helper.js, src/seeds.escrow.cpp, src/seeds.harvest.cpp, src/seeds.pool.cpp, test/escrow.test.js, test/harvest.test.js, test/pool.test.js, test/proposals.test.js
Fixes #224 
- Added new contract call pool.seeds. I added the contract to local and testnet configuration in helper.js but not in main net.
- Changed escrow contract to send the dSeeds as soon as go live is triggerd. It also sends the dSeeds when the locks are claimed.
- Changed harvest so they mint 50% less in case dSeeds > 0, and distribute the other 50% as dSeeds
- Added tests for pool, harvest, escrow and proposals
=> Use buckets to distribute dSeeds and planted bonus alongside harvest #224

include/seeds.proposals.hpp, src/seeds.proposals.cpp, test/proposals.test.js
- Added `migalliances` action, this action will go through all the alliances and pay the missing amount. It is possible to do so, because the current_payout amount wasn't modified, so it's easy to know how much is missing.
- Added a test action `testalliance`
Fixes #329 
No migration nor permissions update is needed.
=> Alliances have not been paid out #329

include/seeds.proposals.hpp, include/seeds.referendums.hpp, src/seeds.proposals.cpp, src/seeds.referendums.cpp
added referendum scope to votes
referendums grabs voice from proposals
missing: need to go through and see if anyone has been removed from voice in the meantime, and remove them from referendum voice too. but - they won't get updated so in any case voice decay should zero them out over time once that's implemented.
=> Fix referendum vote allication

include/seeds.token.hpp, scripts/helper.js, src/seeds.harvest.cpp, src/seeds.token.cpp
Rename minttst to minthrvst since we will use it to mint
in the future adding permissions will be more complicated
remove existing minthrvst permission before deploying this, to be safe
```
target: `${accounts.token.account}@minthrvst`,
action: 'minttst'
action: 'minthrvst'
```
=> rename mintts to minthrvst

include/seeds.history.hpp, scripts/helper.js, src/seeds.history.cpp, src/seeds.scheduler.cpp, test/history.test.js, test/scheduler.test.js
- Added the action `cleanptrxs` to delete the unused ptrx entries
- Added tests
- Added new permissions for scheduler
I configured the action to be executed daily. We should keep the daily transactions in that table so everything works fine.
=> Added cleanptrxs action to delete the unused ptrx entries in history

src/seeds.harvest.cpp, test/harvest.test.js
- Added validation in `harvest::unplant` so organizations can not unplant their fee
- Added tests
No migrations nor settings update are required
=> Organization uses balance instead of planted score for tx limits #320

include/seeds.region.hpp, src/seeds.region.cpp, test/harvest.test.js, test/history.test.js, test/region.test.js
- Added action `createacct` so the founder can create the region account when the regions is active
- Fixed tests
No migrations nor settings update are needed
=> Create account only on active

include/seeds.onboarding.hpp, src/seeds.onboarding.cpp, test/onboarding.test.js
Reason / user story: One of our users signed on with an existing Telos account - not sure how that was possible in the app, but it was possible.
In reality this means she signed on with an account that was not her account! 
She did not realize this until much later, when 15,000 Seeds had been deposited into her account and she tried to use them.
The passport app had stored the public-private key pair that was created at account creation but that keypair was never actually used, because no new account was created.
Pic from the support channel chat
Also: 
minor bugfixes - campinvite auth check didn't work with the random account, replaced binary search with code I can understand and it worked ;) 
fix unit tests
=> Onboarding: Don't accept existing account in accept action

include/seeds.scheduler.hpp, src/seeds.scheduler.cpp, test/scheduler.test.js
added some code to make it easier to schedule moon ops
added some safety check so it's impossible to add a past op (as that would trigger an immediate firing, which would be bad if we have "incprice" or "run proposals"... ;) whoops!!!
Added "addmoonop" so we don't have to figure out unix time stamps - just set the phase as string, and it figures it out.
I also added one to testnet let's see if it fires next time, then can move to mainnet
'''
cleos -u "https://test.hypha.earth" push action cycle.seeds addmoonop '{ 
"id":"inc.lprice",
"action":"incprice",
"contract":"tlosto.seeds",
"quarter_moon_cycles":"1",
"start_phase_name":"First Quarter"
}' -p cycle.seeds@active
> cleost get table cycle.seeds cycle.seeds moonops
{
"rows": [{
"id": "inc.lprice",
"action": "incprice",
"contract": …
=> Moon op improvements

include/seeds.proposals.hpp, scripts/fixprops.js, src/seeds.proposals.cpp
Passport stored JSON in proposal text - this made it non-human readable on the seeds light wallet (or other apps)
Created script to convert the JSON, which also requires mapping keys to titles.
One action takes the data, so we can view it on chain and see whether it is correct
Another action applies the data
Another action to revert changes in case of emergency
This has already been deployed on mainnet, worked
=> fixing proposals script and system

include/seeds.proposals.hpp, src/seeds.proposals.cpp, test/proposals.test.js
also implemented for delegation
Revert votes needs to just revert a user's votes, not use votes from the current vote pool - so on an eval proposal, a revert does not consume votes. It just reverts a yes to a no with the same number of votes.
Fixes #369 for proposals.
Was a bit tricky with vote delegation but I modified the unit tests for reversal of notes so have some confidence it works.
proposals
No other contracts affected
=> revert votes does not use a user's votes

include/seeds.gratitude.hpp, src/seeds.gratitude.cpp, src/seeds.settings.cpp, test/gratitude.test.js
This fixes the code for the `newround` action, that was failing on mainnet because it was running `calc_acks` over too many accounts at once, now we call `calc_acks` recursively.
Also took the opportunity to add acks stats and a new setting to determine how much % of the gratitude pot is saved for the next round (default 0, to behave as now).
=> Fixing Gratitude Tokens recursive new round

src/seeds.gratitude.cpp, test/gratitude.test.js
Checks if the user balance has been inited when calculating acks. This bug should only happen when mixing acks being created with the old version of the gratitude contract, that didn't init that account.
=> check if the user balance has been inited when calculating acks

include/seeds.dao.hpp, include/seeds.proposals.hpp, src/seeds.dao.cpp, src/seeds.proposals.cpp, test/proposals.test.js
We need to use double for quorum to prevent rounding errors...
Bug report
Sorin: 
> Is it too much trouble to use 3 decimals for the code that calculates the percent for quorum?
> For example:
> Last cycle: 1/8 proposals = 0.125 rounded at 0.12. 
> Instead of 0.125 x 13 166 = 1646 trust tokens we had
> 0.12 x 13166 = 1580 trust tokens needed 
> 
> While this cycle we have 1/4 proposals = 0.25 ...no issue here :slight_smile:
> 
> So my question is, how hard is to code that change (from 2 to 3 decimals) and if you want to adjust that to have a more accurate value?
> 
> Thanks!
=> use double for higher precision quorum

src/seeds.settings.cpp
Changing SEEDS settings `gratz.potkp` to 50%, to avoid the campaign reload that ran twice.
=> Changed Gratitude Pot Keep to store 50% of the pot each round

include/seeds.accounts.hpp, include/tables/deferred_id_table.hpp, include/utils.hpp, src/seeds.accounts.cpp, test/accounts.test.js
Fixes #406 
- Added flag delegation
- Added tables `delegators` in accounts
I added two generic functions in`utils`:
- Send deferred transaction
- Delete a table (for use it in the reset function)
I only added those functions to the actions involved in this issue. I think it could help make the contracts look cleaner. Please let me know what you think, I could refactor some contracts to try or if you feel it's not needed I can remove it and change it for the normal way.
No permissions nor settings need to be updated
=> Added flag delegation

src/seeds.dao.cpp, src/seeds.proposals.cpp, test/proposals.test.js
Fix for: https://github.com/JoinSEEDS/seeds-smart-contracts/issues/413
HC (Human cause): Setting parameters on mainnet could cause the rep value we add for delegators to be 0. addrep fails with an error when trying to addrep with 0. Unit tests modified the values and did not test the mainnet values, so unit tests did not cover this.
Fix: 
round the value, which with the current production settings means that delegators will get 1 rep point for entering into the table
Also, check for 0 - in case the settings change such that added rep would be 0, we don't call addrep.
=> Fix vote delegation

include/seeds.dao.hpp, src/proposals/voice_management.cpp, test/dao.test.js
Fix #395
Actions added 
- deletescope
- addvoice
Actions updated
- updatevoice
- updatevoices
Changes made:
`updatevoice` now updates all voices or just a one.
`updatevoices` small change because it calls `updatevoice`.
`deletescope` deletes all voice values from all users for a given proposal scope contained in `scopes` vector.
`addvoice` add all voice values from all users, with its respective value (decay calculated) for a given proposal scope contained in `scopes` vector.
**Contracts to be deployed:**
- No settings added
- No permissions added
- No migrations required
=>  dao.seeds allow voice scopes being added or removed #395 

include/seeds.policy.hpp, scripts/eosjs-port.js, scripts/helper.js, src/seeds.policy.cpp, test/policy.test.js
Expiring policy - set the expiration seconds in the Action call. 
Antonio requested this as to be able to implement authentication
```
createexp(name account, string backend_user_id, string device_id, string signature, string policy, uint64_t expiry_seconds);
```
This is the same as "create" only with an expiry in seconds added to it
see the last field - expiry_seconds
```
expiry
```
Contains these fields:
```
int id - id of the policy (foreign key into devicepolicy table)
int created_at - seconds since 1970 timestamp when the policy was created
int valid_until - seconds since 1970 timestamp when the policy expires 
```
=> Feature: Expiring policy

include/seeds.dao.hpp, include/seeds.proposals.hpp, include/seeds.scheduler.hpp, include/tables/moon_phases_table.hpp, src/seeds.dao.cpp, src/seeds.proposals.cpp, test/dao.test.js, test/proposals.test.js
- Added moon phases table to contracts proposals and dao.
- Now cycle stats for both contracts (proposals and dao) uses moon phases as start and end dates
Fixes #412 
Contracts to be deployed:
No permissions nor settings need to be updated
=> Fix cyclestats start_time and end_time using moon cycle times #412

include/seeds.proposals.hpp, src/seeds.proposals.cpp, test/proposals.test.js
implements:
https://github.com/JoinSEEDS/seeds-smart-contracts/issues/436
also logic check - planted needs to be < max invite value
=> enforce max limits for invite campaigns

scripts/onboarding_script.js
The existing onboarding script includes a `bulk_invite` command, which generates a quantity of invites, places them on chain, and saves a file `secrets_nnn.csv` containing the secrets and hashes.
This PR adds an additional output file `invitelist_nnn.txt`  containing lines of the form
```
https://joinseeds.app.link/accept-invite?invite-secret=354a364a624d46784c546d645a6855704755613767437167517674705a684c47
```
This is consistent with the invite "export" function of the Seeds Global Passport web application, and can be imported to the invite manager at https://invites.joinseeds.earth/login
=> Bulk onboarding script update for invite manager
