include/seeds.token.hpp, scripts/balancecheck.js, scripts/seeds.js, src/seeds.token.cpp, test/token.test.js
- added updatecirc action
- some improvements to scripts
=> Circulating Supply

src/seeds.proposals.cpp, test/proposals.test.js
We had a proposals majority setting already, but we were not using it in the contract
Probably an oversight - this fixes it, added more unit tests also to ensure it works.
=> use propmajoriy setting for proposals

include/seeds.proposals.hpp, scripts/genesis.js, src/seeds.proposals.cpp, test/proposals.test.js
this fixes the issue where new citizens would never receive voice if voice was not explicitly set for them
=> add new citizens to voice table on new cycle

include/seeds.exchange.hpp, scripts/helper.js, src/seeds.exchange.cpp, test/exchange.test.js
changed exchange contract to accept usd payments from API
tlos to seeds works the same as before
=> Asset exchange

include/seeds.proposals.hpp, src/seeds.proposals.cpp, test/proposals.test.js
- Implemented the cancel proposal action
- Implemented refund action
- Validate only the proposal's owner can stake
=> Cancel proposal action

include/contracts.hpp, include/seeds.proposals.hpp, scripts/helper.js, src/seeds.proposals.cpp, test/proposals.test.js
Phase 1: Deploy proposals without the deferred transaction that auto-runs on the next cycle
(in progress)
Phase 2: Fix bugs related to not having permission for gift.seeds, allies.seeds, milest.seeds
Phase 3: Add proposals oncycle to scheduler, with the next moon cycle set as start date.
=> Proposals Bugfix for Campaign types use scheduler

include/seeds.accounts.hpp, src/seeds.accounts.cpp, src/seeds.settings.cpp, test/accounts.test.js
deploy settings, accounts, call reset on settings
=> vouch bonus 10, 20, stored in settings

include/seeds.proposals.hpp, scripts/helper.js, src/seeds.proposals.cpp, src/seeds.settings.cpp, test/proposals.test.js
- Added a neutral vote
- Added constants trust, distrust and abstain
- Added `participants` table
- Added +1 (configurable) reward when a user enters to the `participants` table
- Added +5 (configurable) reward when a user votes for all active proposals
- Added `erasepartpts` action
=> Issue 57 and issue 59

include/seeds.accounts.hpp, src/seeds.accounts.cpp, src/seeds.settings.cpp, test/accounts.test.js
=> all citizenship path values are settings #83

include/seeds.token.hpp, scripts/helper.js, src/seeds.scheduler.cpp, src/seeds.settings.cpp, src/seeds.token.cpp, test/scheduler.test.js, test/token.test.js
- Added a validation in transfer action from token to limit the number of transactions per user
- Added settings txlimit.mul and txlimit.min
- Added reset weekly to the scheduler
- Added permission to token
=> Issue Transaction Limit By Planted Seeds #51

include/seeds.exchange.hpp, src/seeds.exchange.cpp, test/exchange.test.js
Added price history table and priceupdate action
=> Create Table with price history #82

test/harvest.test.js
The error wasn't the one shown in the issue, but the test still failed. However it just failed because transactions needed some time to execute so I added some sleeps. 
I also had to comment this line in my nodeos as the comment suggests to run the tests:
https://github.com/JoinSEEDS/seeds-smart-contracts/blob/master/src/seeds.history.cpp#L102
I also noticed that the key variable used to identify the deferred transaction would be the same for two users with the same number of recorded transactions and thus if those two users make a transaction at the same time one of the transactions will fail. This could be really hard to happen in production but it was notorious in the tests so I just wanted to mentioned it.
https://github.com/JoinSEEDS/seeds-smart-contracts/blob/master/src/seeds.history …
=> Fix harvest test #77

include/seeds.history.hpp, src/seeds.history.cpp
This helps the wallet figure out how many transactions a user has
=> added numtrx

include/seeds.proposals.hpp, src/seeds.proposals.cpp, src/seeds.settings.cpp, test/proposals.test.js
- Added parameters: `propmaxstake` and `propstakeper`
- Added validations to: `vote_aux`, `onperiod` and `stake`
=> Funding Fee and Referendum fee burning #61

include/seeds.proposals.hpp, src/seeds.proposals.cpp, test/proposals.test.js
- Added batches to the update voice procedure
- Added `updatevoices` and `updatevoices` actions
=> Iterative Vote distribution #92

include/seeds.organization.hpp, scripts/helper.js, src/seeds.organization.cpp, src/seeds.scheduler.cpp, test/organization.test.js, test/scheduler.test.js
- Added functions: registerapp, banapp, appuse, cleandaus and cleandau
- Added app_table, dau_table and dau_history_table
=> App tracking #81

include/seeds.exchange.hpp, src/seeds.exchange.cpp, test/exchange.test.js
Migrate allows us to migrate to a new contract
=> Add pause feature to exchange

include/seeds.accounts.hpp, include/seeds.proposals.hpp, src/seeds.accounts.cpp, src/seeds.proposals.cpp, src/seeds.settings.cpp, test/proposals.test.js
Finished demote inactive citizen. Added updateactivs and updateactive to proposals, Modified makecitizen to add an active entry in proposals state.
=> Demote Inactive Citizens to Resident - they can come back! #113

include/seeds.forum.hpp, scripts/helper.js, src/seeds.forum.cpp, src/seeds.scheduler.cpp, src/seeds.settings.cpp, test/forum.test.js, test/scheduler.test.js
- Added forum ranks, and give reputation. 
- Added tables `active` and `size`. Modified `forumrep` table  
- Added forum parameters to settings. 
- Added functions to scheduler.
- Added tests
=> Forum Rep Points #109

include/seeds.proposals.hpp, src/seeds.proposals.cpp, test/proposals.test.js
- Added evaluation phase to proposals
- Added tests
- Added new fields to proposal table
About the Max's Document mentioned in the last meeting, we think this new table structure will suppose a great change in the way the information is stored, and as it is still pretty new, it might have some issues not yet discovered. So that's why I only added the extra fields to the proposals table.
=> Feature/evaluation phase #18

include/seeds.proposals.hpp, src/seeds.proposals.cpp, src/seeds.settings.cpp, test/proposals.test.js
- Added new function to calculate the quorum
- Added size table
- Added tests
#129
=> Proposal changes - flexible quorum #129

include/seeds.guardians.hpp, scripts/helper.js, src/seeds.guardians.cpp, test/guardians.test.js
Smart contract for key guardians
deployed at guard.seeds
=> Guardians smart contract WIP

include/seeds.accounts.hpp, include/seeds.history.hpp, src/seeds.accounts.cpp, src/seeds.history.cpp, src/seeds.settings.cpp, test/accounts.test.js
This is a solution for issue #174, reverting the rewards calculation from being based on current SEEDS exchange price to an exponential decaying formula.
=> Implemented new decaying formula

include/seeds.proposals.hpp, src/seeds.proposals.cpp, src/seeds.settings.cpp, test/proposals.test.js
- Added functions to delegate and cancel delegation of trust
- Added tests
- Added new parameter `votedel.mul` to settings
=> Basic Delegate Trust #58

include/seeds.settings.hpp, include/tables/config_float_table.hpp, src/seeds.settings.cpp
- Added new table to store floating points settings
=> Settings with floating point values #182

include/seeds.accounts.hpp, src/seeds.accounts.cpp, src/seeds.settings.cpp, test/accounts.test.js
The main issue that was fixed here is #151, with tests, but no migration yet.
Also added the needed settings for #150 (but besides that, the change to actually use this setting is at Passport and Light Wallet)
Checked issue #160 and it's already separated, from what I can reckon.
=> Small fixes for alignment with constitution

include/seeds.harvest.hpp, src/seeds.harvest.cpp, src/seeds.settings.cpp
Added setting to control the number of cycles to take into account for transaction points calculation
=> Transaction Point Cycle Length setting #153

include/seeds.exchange.hpp, src/seeds.exchange.cpp, test/exchange.test.js
handle HUSD same way we used to handle TLOS
differences: HUSD is 2 digits of precision and comes from husd.hypha token contract.
=> handle HUSD

include/contracts.hpp, include/seeds.bracelet.hpp, scripts/helper.js, src/seeds.bracelet.cpp, test/bracelet.test.js
- Added new contract bracelet
- Added tests
The `transfer` action, enforces the usage of the `bracelet` permission. The `bracelet` permission should be created by the user as well as the linkAuth. There is an example of this in the tests.
I didn't create the contract in helper.js for testnet nor mainnet, just in case
=> Bracelet management contract (bag of seeds) #197

include/contracts.hpp, include/seeds.pouch.hpp, scripts/helper.js, src/seeds.pouch.cpp, test/pouch.test.js
Changed the name of the contract from bracelet to pouch
tested, compiles
=> rename bracelet to pouch

src/seeds.proposals.cpp, src/seeds.settings.cpp, test/proposals.test.js
- Added a validation to avoid cycles
- Added a test
I thought it could also be convenient to have some depth setting so the DAG doesn't extend forever, that's why I added it. I set the depth to 100.
=> Added cycles validation when delegating trust

scripts/helper.js, src/seeds.harvest.cpp, src/seeds.scheduler.cpp, test/scheduler.test.js
- Added `runharvest` to scheduler `reset`
- Added permissions
- Added tests in scheduler
- Modified the `runharvest` action so it won't crash in case mint rate is empty
=> Call Harvest from the scheduler #212

include/seeds.referendums.hpp, src/seeds.referendums.cpp, test/referendums.test.js
- Added referendums consider the setting's impact to determine the unity and quorum thresholds
- Modified tests
=> Referendum low med high impact settings #215

include/seeds.accounts.hpp, package.json, scripts/deploy.js, scripts/eosjs-port.js, scripts/helper.js, src/seeds.accounts.cpp, test/accounts.test.js, test/onboarding.test.js
- Added a new table for vouches
- Added tests
- Added a migration function
=> Accept Vouch and Un-vouch on penalty #233

include/seeds.accounts.hpp, scripts/helper.js, src/seeds.accounts.cpp, src/seeds.settings.cpp, src/seeds.token.cpp, test/accounts.test.js
From constitution
- Different cbps for orgs and individuals, new settings for it
- Referrer gets cbp, not voucher
=> Distribute Community Building Points only referrer

include/seeds.proposals.hpp, src/seeds.proposals.cpp
onperiod and testperiod now use vote power calculation for quorum
=> update for real quorum calculation, using vote power

include/seeds.accounts.hpp, src/seeds.accounts.cpp
Migration for new vouch tables - please review
=> migrate method which does not add or remove rep from anyone

scripts/eosjs-port.js, src/seeds.history.cpp, test/proposals.test.js
New quorum calculation upset many unit tests, fixing it up so they all pass once again
=> Unit tests updated for new quorum calculations

src/seeds.harvest.cpp
- Fixed the batch size to 10 to avoid time outs in harvest distribution
=> Fixed batch size for the harvest distribution

include/seeds.accounts.hpp, src/seeds.accounts.cpp, src/seeds.settings.cpp, test/accounts.test.js
* Setting for ref point rewards added
* Code and tests changed for ref point setting
* Some unused settings removed
* Some additional settings added - mainly for the 5 levels of organizations we now have in the game guide
As per game guide & constitution
- deploy settings, accounts
- updateSettings
=> added settings for vouch reputation rewards

include/seeds.escrow.hpp, include/seeds.proposals.hpp, scripts/helper.js, src/seeds.escrow.cpp, src/seeds.proposals.cpp, test/escrow.test.js, test/proposals.test.js
- Added new actions to allow escrow contract interact with proposals contract
- Fixed escrow tests that were broken
- Added tests for proposals
**Deployment**
Permissions need to be updated
Migrations are not needed
=> Alliance shares can be voted down #241

src/seeds.harvest.cpp, src/seeds.settings.cpp
New feature we now have a configurable inflation rate per period
It's set to 0, so nothing changed. 
- Harvest
- Settings
- updateSettings
=> added inflation rate setting as per game guide

include/seeds.onboarding.hpp, src/seeds.onboarding.cpp
Preparing to have an automated refund scheme after 1 cycle, so old invites get refunded
It will use this method to  clean up index ranges
=> Cleanup fix up for campaigns

include/seeds.harvest.hpp, src/seeds.harvest.cpp, src/seeds.settings.cpp, test/harvest.test.js
Fixes #251 
Contracts that need deployment:
=> Only Org levels 3, 4, and 5 are eligible for receiving part of the harvest #251

include/seeds.accounts.hpp, include/seeds.history.hpp, scripts/helper.js, src/seeds.accounts.cpp, src/seeds.history.cpp, test/history.test.js
- Added new table to store the actions that triggers the cbp reward.
- Added deferred transaction to calculate the actions
- Added permission to history@eosio.code to execute accounts@active
- Added new action in accounts to give cbp
- Added tests
Implements #269 
**Deployment**
=> Community Building Points for supporting local / regen / triving org #269

include/contracts.hpp, include/seeds.msig.hpp, scripts/seeds.js, src/seeds.msig.cpp
this is a 1:1 copy of the eosio.msig contract
=> added msig contract, remove special case for msig code

docs/accounts.html, docs/escrow.html, docs/exchange.html, docs/forum.html, docs/gratitude.html, docs/guardians.html, docs/harvest.html, docs/history.html, docs/index.html, docs/onboarding.html, docs/organization.html, docs/pouch.html, docs/proposals.html, docs/region.html, docs/scheduler.html, docs/service.html, docs/token.html
Updating contract documentation.
Migration docs from bioregion -> region
=> Contracts documentation update

include/seeds.onboarding.hpp, scripts/helper.js, src/seeds.onboarding.cpp, src/seeds.scheduler.cpp, test/onboarding.test.js, test/scheduler.test.js
- Added `chkcleanup` action to onboarding and added to the scheduler
- Added tests for onboarding and refactored scheduler tests
Fixes #328 
=> Claim back unused invites #328

include/seeds.settings.hpp, src/seeds.settings.cpp, test/settings.test.js
just added a remove action because there's some stray settings on mainnet we need to clean up
=> added remove method for cleanup purposes

include/seeds.onboarding.hpp, src/seeds.onboarding.cpp, test/onboarding.test.js
Added a reward() action to onboarding
Reward is almost the same as acceptexist() but checks that the user is already a Seeds account.
Fixed up and added unit tests as well
I had to shuffle the auth check into the actions as each action has different auth checks. 
Deploy onboarding contract, no other changes
=> added reward action to onboarding

include/seeds.onboarding.hpp, src/seeds.onboarding.cpp, test/onboarding.test.js
As per Alex requests, rewards are paid out in liquid seeds, not planted
=> rewards are paid out in liquid seeds, no planting

scripts/eosjs-port.js, src/seeds.proposals.cpp, test/proposals.test.js
1 year eval period for alliances, but instant payout
fixed some unit tests, error messages
=> made alliance periods longer

include/seeds.proposals.hpp, src/seeds.proposals.cpp, test/proposals.test.js
=> banned check on eval proposal

include/seeds.referendums.hpp, src/seeds.referendums.cpp, test/referendums.test.js
App had many errors causing users to send too much stake to the contract
Adding refundstake action so they can get their Seeds back
=> refundstake added

src/seeds.proposals.cpp, test/proposals.test.js
Implements: https://github.com/JoinSEEDS/seeds-smart-contracts/issues/435
=> max alliance ask

include/seeds.accounts.hpp, scripts/helper.js, src/seeds.accounts.cpp, test/accounts.test.js
fixes #438
Note: I left all the existing methods intact, just added a shortcut when 3+ citizens vouch for a user, that user can become a citizen instantly.
=> citizenship ceremony implementation

include/seeds.accounts.hpp, src/seeds.accounts.cpp, test/accounts.test.js
=> [Governance Referendum #4] remove seeds payout

include/hypha.sale.hpp, src/hypha.sale.cpp, test/sale.test.js
Implemented whitelist, tests
fixes https://github.com/hypha-dao/dho-web-client/issues/1733
=> added whitelist, tests
